language: python
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cp config-secret-stub.ini config-secret.ini
script:
  - pytest test/unit
  - mypy run_fal.py fal
after_success:
  - pytest --cov fal test/
  - codecov
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
