language: python
cache: pip
install:
  - pip install -r requirements.txt
  - pip install git+git://github.com/AWConant/jikanpy.git
  - pip install pytest-cov codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cp config-secret-stub.ini config-secret.ini
script: pytest test/unit
after_success:
  - pytest --cov fal test/
  - codecov
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
