language: python
cache: pip
python:
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install git+git://github.com/AWConant/jikanpy.git
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script: pytest
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true