version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            pip install pytest-cov codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Run tests and mypy
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            cp config-secret-stub.ini config-secret.ini
            . venv/bin/activate
            pytest test/unit
            mypy run_fal.py fal

      - run:
          name: Run codecov
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            . venv/bin/activate
            pytest --cov fal test/unit
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
