version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            export PIPENV_VENV_IN_PROJECT=1
            pip install pipenv
            pipenv install --dev
            pipenv install pytest-cov codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run tests and mypy
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            cp config-secret-stub.ini config-secret.ini
            pipenv run pytest test/unit/
            pipenv run mypy run_fal.py fal/

      - run:
          name: Run codecov
          command: |
            set +e
            export PYTHONPATH=$PYTHONPATH:$(pwd)
            pipenv run pytest --cov fal test/
            pipenv run codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
